# Generated by Django 5.1.3 on 2025-04-22 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Technology"),
                            (1, "Product"),
                            (2, "Operation"),
                            (3, "Design"),
                        ],
                        verbose_name="Job Type",
                    ),
                ),
                ("job_name", models.CharField(max_length=250, verbose_name="Job Name")),
                (
                    "job_city",
                    models.SmallIntegerField(
                        choices=[(0, "Taipei"), (1, "Tokyo"), (2, "New York")],
                        verbose_name="City",
                    ),
                ),
                (
                    "job_repository",
                    models.TextField(max_length=1024, verbose_name="Job Repository"),
                ),
                (
                    "job_requirements",
                    models.TextField(max_length=1024, verbose_name="Job Requirements"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
            ],
        ),
    ]
