# Generated by Django 5.1.3 on 2025-04-23 08:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name='job_repository',
            new_name='job_responsibility',
        ),
    ]
